name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  [push, pull_request]

# [Building and testing Node.js | GitHub Documentation](https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs)
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout branch on which commit was performed
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci
        run: npm ci
      - name: npm run build:maps-directions:react
        run: npm run build:maps-directions:react
      - name: Archive build as artifact
        uses: actions/upload-artifact@v2
        with:
          name: build_artifact
          path: '*dist/'
          retention-days: 1

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          # branch gh-pages has already been created by
          # hand when setting up GitHub Pages (see README.md)
      - name: Enter GitHub credentials
        run: |
          git config --global user.name 'DamienToomey'
          git config --global user.email 'DamienToomey@users.noreply.github.com'
          git remote set-url origin ssh://git/DamienToomey:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        # [Push to origin from GitHub action | Stack Overflow](https://stackoverflow.com/questions/57921401/push-to-origin-from-github-action)
      - name: Delete folders/files on branch gh-pages
        run: git rm --ignore-unmatch -rf .
        # Initial state of branch gh-pages is an empty branch
        # --ignore-unmatch: exit with a zero status even if nothing matched
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build_artifact
      - name: Rename dist folder to app folder
        run: |
          git add dist/
          git mv dist/ app/
      - name: Push app folder to gh-pages branch
        run: |
          git commit -m "Deploying build to GitHub Pages"
          git push origin gh-pages
